---
- name: Creating Elasticsearch data folder
  file:
    dest: '{{ elastic_path }}/elasticsearch'
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0755

- name: Configure kernel parameters
  sysctl:
    name: '{{ item.variable }}'
    value: '{{ item.value }}'
    state: present
    reload: yes
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/20-sysctl.conf
  with_items:
    - '{{ elastic_kernel_parameters }}'

- name: Elasticsearch Configure file transfer
  template:
    src: 'elasticsearch.yml.j2'
    dest: '/etc/elasticsearch/elasticsearch.yml'
    owner: root
    group: root
    mode: 0644
  register: es_config

- name: Elasticsearch JVM options configuration
  lineinfile:
    state: present
    dest: '/etc/elasticsearch/jvm.options'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^-Xms', line: '-Xms{{ elastic_heap_size }}' }
    - { regexp: '^-Xmx', line: '-Xmx{{ elastic_heap_size }}' }
  register: es_jvm

- name: Elasticsearch system configuration
  lineinfile:
    state: present
    dest: '/etc/sysconfig/elasticsearch'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^MAX_OPEN_FILES', line: 'MAX_OPEN_FILES=65535' }
    - { regexp: '^MAX_LOCKED_MEMORY', line: 'MAX_LOCKED_MEMORY=unlimited' }
    - { regexp: '^MAX_MAP_COUNT', line: 'MAX_MAP_COUNT=262144' }
  register: es_sysconfig

- name: Elasticsearch PKI file transfer
  copy:
    src: 'ssl/'
    dest: '/etc/elasticsearch/ssl'
    owner: 'root'
    group: 'root'
    mode: 0644
  register: es_pki
