---
- name: Add Prometheus elasticsearch exporter YUM repositories.
  yum_repository:
    name: '{{ elastic_exporter_repo_name }}'
    description: '{{ elastic_exporter_repo_name }} YUM repository'
    file: '{{ elastic_exporter_repo_name }}'
    baseurl: '{{ elastic_exporter_repo_url }}'
    gpgcheck: 'no'
    sslverify: 'no'
    timeout: '60'

- name: Install the Prometheus elasticsearch exporter packages.
  yum:
    name: '{{ elastic_exporter_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 5
  delay: 2

- name: Prometheus elasticsearch exporter configure file transfer.
  template:
    src: 'elasticsearch_exporter.default.j2'
    dest: '/etc/default/elasticsearch_exporter'
    owner: 'prometheus'
    group: 'prometheus'
    mode: '0640'
  notify: 'Ensure Elasticsearch exporter service is enabled.'
