---
- name: Allow Elasticsearch service port
  firewalld:
    port: '{{ item }}/tcp'
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  with_items:
    - '{{ elastic_port_rest }}'
    - '{{ elastic_port_node }}'
    - '{{ elastic_port_exporter }}'
