---
- name: Allow Elasticsearch service port
  firewalld:
    port: '{{ item.value }}/tcp'
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  with_dict: '{{ elastic_port_arg }}'
