---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Include tasks for specific OS
  include: '{{ ansible_os_family }}.yml'

- name: Straight to getenforce selinux status
  include: 'selinux.yml'

- name: Include firewall tasks
  include: 'firewall.yml'

- name: Configuration the consul
  include: 'configureation.yml'

- name: Install x-pack plugins
  include: 'xpack.yml'
  when: elasticsearch_xpack

- name: Reload the Elasticsearch service
  shell: echo ''
  notify: 'Ensure Elasticsearch service is enabled'
  when: es_update|changed or es_config|changed or es_xpack_state|changed

- name: Force the handler to run immediately
  meta: flush_handlers

- name: Include authentication tasks
  include: 'authentication.yml'
  when:
    - elasticsearch_xpack 
    - es_xpack_state|changed or es_xpack_state|changed

- name: Include prometheus exporter tasks
  include: 'exporter.yml'

- include_tasks: 'register.yml'
  when: consul_is_register
