---
- name: Gather Elastic node variables for cluster
  set_fact:
    elastic_servers: "\
      {% set _elastic_servers = [] %}\
      {% for host in groups[group_names[-1]] %}\
        {% set _elastic_cluster = hostvars[host]['elastic_cluster'] | default('', true) %}\
        {% if ( _elastic_cluster == hostvars[host]['elastic_cluster']) %}\
          {% if _elastic_servers.append(hostvars[host]['ansible_host']) %}{% endif %}\
        {% endif %}\
      {% endfor %}\
      {{ _elastic_servers }}"
  when: elastic_servers is not defined

- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Include tasks for specific OS
  include: '{{ ansible_os_family }}.yml'

- name: Straight to getenforce selinux status
  include: 'selinux.yml'

- name: Include firewall tasks
  include: 'firewall.yml'

- name: Configuration the consul
  include: 'configureation.yml'

- name: Install x-pack plugins
  include: 'xpack.yml'
  when: elastic_auth

- name: Reload the Elasticsearch service
  shell: echo ''
  notify: 'Ensure Elasticsearch service is enabled'
  when: es_update is changed or es_config is changed or es_xpack_state is changed

- name: Force the handler to run immediately
  meta: flush_handlers

- name: Include authentication tasks
  include: 'authentication.yml'
  when:
    - elastic_auth 
    - es_xpack_state is changed or es_xpack_state is changed

- name: Include prometheus exporter tasks
  include: 'exporter.yml'

- include_tasks: 'register.yml'
  when: consul_is_register
