---
- name: 'Add Elasticsearch {{ elastic_version.split(".")[0] }} YUM repositories'
  yum_repository:
    name: '{{ elastic_repo_name }}'
    description: '{{ elastic_repo_name }} YUM repository'
    file: '{{ elastic_repo_name }}'
    baseurl: '{{ elastic_artifacts_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the Elasticsearch dependents packages
  yum:
    name: '{{ item }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  loop: '{{ elastic_dependent_packages|flatten(levels=1) }}'
  register: yum_status
  until: yum_status is succeeded
  retries: 3
  delay: 5

- name: Install the Elasticsearch packages
  yum:
    name: '{{ item }}'
    state: 'present'
    enablerepo: '{{ elastic_repo_name }}'
    validate_certs: 'no'
    update_cache: 'yes'
    disable_gpg_check: 'yes'
  loop: '{{ elastic_packages|flatten(levels=1) }}'
  register: es_update
  until: es_update is succeeded
  retries: 3
  delay: 5
