---
- name: 'Add Elasticsearch {{ elastic_version }} YUM repositories'
  yum_repository:
    name: '{{ elastic_repo_name }}'
    description: '{{ elastic_repo_name }} YUM repository'
    file: '{{ elastic_repo_name }}'
    baseurl: '{{ elastic_artifacts_repo_url }}'
    gpgcheck: no

- name: Install the Elasticsearch packages
  yum:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - '{{ elastic_packages }}'
  register: es_update
