---
- name: 'Add Elasticsearch {{ elasticsearch_version }} YUM repositories'
  yum_repository:
    name: '{{ elasticsearch_repo_name }}'
    description: '{{ elasticsearch_repo_name }} YUM repository'
    file: '{{ elasticsearch_repo_name }}'
    baseurl: '{{ elasticsearch_artifacts_repo_url }}'
    gpgcheck: no

- name: Install the Elasticsearch packages
  yum:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - '{{ elasticsearch_packages }}'
  register: es_update
