---
- name: 'Get getenforce binary'
  stat:
    path: '/usr/sbin/getenforce'
  register: getenforce_bin
  become: yes

- name: 'Collect getenforce output'
  command: getenforce
  register: sestatus
  when: 'getenforce_bin.stat.exists'
  changed_when: false
  become: yes

- name: 'Set elasticsearch_selinux to true if getenforce returns Enforcing or Permissive'
  set_fact:
    elasticsearch_selinux: '{{ true }}'
  when: 'getenforce_bin.stat.exists and ("Enforcing" in sestatus.stdout or "Permissive" in sestatus.stdout)'

- name: 'Allow elasticsearch to listen on tcp port'
  seport:
    ports: '{{ item.value }}'
    proto: 'tcp'
    setype: 'http_port_t'
    state: 'present'
  loop: '{{ elasticsearch_port_arg|dict2items }}'
  when:
    - elasticsearch_selinux
