---
- name: Ensure Elasticsearch service is enabled.
  systemd:
    name: 'elasticsearch.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  async: 1
  poll: 0

- name: Ensure Elasticsearch exporter service is enabled.
  systemd:
    name: 'elasticsearch_exporter.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'